// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmpgLuXIS7nmMS0H1TdnBVPNZMe0BQCkw',
    appId: '1:904569072645:web:fd035d954f26ca7e24c06c',
    messagingSenderId: '904569072645',
    projectId: 'elearning-52c4b',
    authDomain: 'elearning-52c4b.firebaseapp.com',
    storageBucket: 'elearning-52c4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF3Fhvr7qoIhCSC4ep7QjFfkqmK42NM_M',
    appId: '1:904569072645:android:189a82d554741fc224c06c',
    messagingSenderId: '904569072645',
    projectId: 'elearning-52c4b',
    storageBucket: 'elearning-52c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABEVr0EI_sglVfLkSOytfPafhFcLRv6_Q',
    appId: '1:904569072645:ios:019c9bd6a15c6c7124c06c',
    messagingSenderId: '904569072645',
    projectId: 'elearning-52c4b',
    storageBucket: 'elearning-52c4b.firebasestorage.app',
    iosBundleId: 'com.example.monElearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABEVr0EI_sglVfLkSOytfPafhFcLRv6_Q',
    appId: '1:904569072645:ios:019c9bd6a15c6c7124c06c',
    messagingSenderId: '904569072645',
    projectId: 'elearning-52c4b',
    storageBucket: 'elearning-52c4b.firebasestorage.app',
    iosBundleId: 'com.example.monElearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmpgLuXIS7nmMS0H1TdnBVPNZMe0BQCkw',
    appId: '1:904569072645:web:160cd51ce4b07fbf24c06c',
    messagingSenderId: '904569072645',
    projectId: 'elearning-52c4b',
    authDomain: 'elearning-52c4b.firebaseapp.com',
    storageBucket: 'elearning-52c4b.firebasestorage.app',
  );
}
